[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add='''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
source ~/.config/nvim/plugins/rust.rc.vim
'''

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.rc.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = '5t111111/denite-rails'
hook_add = '''
source ~/.config/nvim/plugins/denite-rails.rc.vim
'''

[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo ='plasticboy/vim-markdown'
hook_add = '''
source ~/.config/nvim/plugins/markdown.rc.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
source ~/.config/nvim/plugins/previm.rc.vim
'''

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = '''
source ~/.config/nvim/plugins/seiya.rc.vim
'''

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
source ~/.config/nvim/plugins/vim-go.rc.vim
'''

[[plugins]]
repo = 'zchee/deoplete-go'
hook_add = '''
source ~/.config/nvim/plugins/deo-go.rc.vim
'''

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'racer-rust/vim-racer'
hook_add = '''
source ~/.config/nvim/plugins/racer.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'mbbill/undotree'

